version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80"
    networks:
      - app
    volumes:
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./project:/var/www/project
  
  db:
    image: mysql:8
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080"
    depends_on:
      - db
    networks:
      - app

volumes:
  mysql: {}

networks:
  app: {}